### ISSUE TITLE
Broken time parser

### ISSUE THREAD

**Issue by dungwinux** [minhducsun2002/miyu#8]
## Description
The render of negative time (BC) is incorrect. Here is Wafter server info:

```json
{
  "name": "リライト contest",
  "mode": "OI",
  "startTime": "-271821-04-20T00:00:00.000Z",
  "endTime": "+275760-09-13T00:00:00.000Z",
  "probList": [
    "A",
    "ASD",
    "GCD",
    "LARES",
    "TABLE"
  ],
  "allowedCodeExt": [
    ".C",
    ".CPP",
    ".JAVA",
    ".PAS"
  ]
}
```

## Pictures

![image](https://user-images.githubusercontent.com/23451424/76230274-0f340b80-6256-11ea-8fb5-2d5db277b6f3.png)
![image](https://user-images.githubusercontent.com/23451424/76230323-1f4beb00-6256-11ea-8fd8-f19a84491cdd.png)

**Comment by minhducsun2002** [comment]
This problem comes from JavaScript itself.
I tried this on Node.js 13.10.1, and it yields the same result :
```
$ node
Welcome to Node.js v13.10.1.
Type ".help" for more information.
> new Date("-271821-04-20T00:00:00.000Z")
-271821-04-20T00:00:00.000Z
> new Date("-271821-04-20T00:00:00.000Z").toLocaleString()
'4/20/271822, 7:06:40 AM'
```
IMO, using BC dates is never a good idea, the calendar back then wasn't even standardised. Not gonna fix this.
